s = input()
s = s.replace('a', '')
s = s.replace('o', '')
s = s.replace('y', '')
s = s.replace('e', '')
s = s.replace('u', '')
s = s.replace('i', '')
s = s.replace('A', '')
s = s.replace('O', '')
s = s.replace('Y', '')
s = s.replace('E', '')
s = s.replace('U', '')
s = s.replace('I', '')
print(s)